Ext.define('Project1.project1.shared.com.model.testboundedcontext.NativeQueryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "pRIMARYKEY1",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "fNAME",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "aGE",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "dATEOFBIRTH",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "sALARY",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "iSEMP",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "rUSURE",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "cREATEDBY",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "cREATEDDATE",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "uPDATEDBY",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "uPDATEDDATE",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "vERSIONID",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "aCTIVESTATUS",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "tXNACCESSCODE",
          "type": "int",
          "defaultValue": ""
     }]
});